// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs7D-GpeYpC-iEr27aPuVwq5A3i4aVPRk',
    appId: '1:46365526449:web:103ed995fcb752438a1590',
    messagingSenderId: '46365526449',
    projectId: 'ecommerce-a272b',
    authDomain: 'ecommerce-a272b.firebaseapp.com',
    storageBucket: 'ecommerce-a272b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9gezCCVWzEpbuW6ok7o9mKmo4icB13Ts',
    appId: '1:46365526449:android:54a36af1083e5dcf8a1590',
    messagingSenderId: '46365526449',
    projectId: 'ecommerce-a272b',
    storageBucket: 'ecommerce-a272b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHd0Cyt-PrjPcpUSNVwn4oCuQsTg6Oc2k',
    appId: '1:46365526449:ios:f53d0ea47014ae6a8a1590',
    messagingSenderId: '46365526449',
    projectId: 'ecommerce-a272b',
    storageBucket: 'ecommerce-a272b.appspot.com',
    iosClientId: '46365526449-vhq28ujd9i4pc594f36rcam2lddudmv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHd0Cyt-PrjPcpUSNVwn4oCuQsTg6Oc2k',
    appId: '1:46365526449:ios:14b3d7663386125f8a1590',
    messagingSenderId: '46365526449',
    projectId: 'ecommerce-a272b',
    storageBucket: 'ecommerce-a272b.appspot.com',
    iosClientId: '46365526449-u5t8bfsj1uekm7d5f6ega5vkt8ejjjsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp.RunnerTests',
  );
}
